# Generated by Django 4.0.4 on 2022-07-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertask',
            name='user',
        ),
        migrations.AddField(
            model_name='answertask',
            name='student',
            field=models.ManyToManyField(related_name='answers', to='course.student'),
        ),
        migrations.AlterField(
            model_name='answertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course.task'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='courses', to='course.category'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='course.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.course'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='course.course'),
        ),
    ]
