# Generated by Django 4.0.4 on 2022-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('In progress', 'Курс идет'), ('Wait for group', 'Набор группы')], default='Wait for group', max_length=16),
        ),
    ]
