# Generated by Django 4.0.4 on 2022-07-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_student_country_remove_student_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_as_text', models.TextField()),
                ('answer_as_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('task', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.AddField(
            model_name='answertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task'),
        ),
        migrations.AddField(
            model_name='answertask',
            name='user',
            field=models.ManyToManyField(related_name='answers', to='course.userprofile'),
        ),
    ]
