# Generated by Django 4.0.4 on 2022-07-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_answertask_user_answertask_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='course.userprofile'),
        ),
    ]
